version: '3.8'

services:
  django:
    build: .
    volumes:
      - .:/opt/services/django/src
    env_file:
      - .env
    networks:
      - datadog_network
    depends_on:
      - postgres
  
  nginx:
    image: nginx:1.18.0
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - django
    networks:
      - datadog_network
    ports:
      - 8000:80
    labels:
      com.datadoghq.ad.check_names: '["nginx"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: '[{"nginx_status_url": "http://%%host%%:81/nginx_status"}]'

  postgres:
    image: postgres:12.3
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    env_file:
      - config/postgres/.env
    networks:
      - datadog_network
    ports:
      - '5432:5432'
    labels:
      com.datadoghq.ad.check_names: '["postgres"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: '[{"host":"%%host%%", "port":5432,"username":"${DATADOG_USER}","password":"${DATADOG_PASSWORD}"}]'
    
  datadog:
    image: datadog/agent:7.19.2
    env_file:
      - config/datadog/.env
    networks:
      - datadog_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro

networks:
  datadog_network:
    driver: bridge  

volumes:
  postgres_volume: